### ISSUE TITLE
i got error when i get shell

### ISSUE THREAD

**Issue by Mehran** [calebstewart/pwncat#16]
```[+] received connection from 10.10.207.195:57025
[+] new host with hash a7f1aff71cccccca5e81df796583fb4f (hostname: b'freebsd', mac: 02:ce:64:a0:e4:cc)
[-] identifying init systemTraceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/Downloads/pwncat/pwncat/__main__.py", line 84, in <module>
    main()
  File "/root/Downloads/pwncat/pwncat/__main__.py", line 29, in main
    pwncat.victim.command_parser.dispatch_line(
  File "/root/Downloads/pwncat/pwncat/commands/__init__.py", line 287, in dispatch_line
    command.run(args)
  File "/root/Downloads/pwncat/pwncat/commands/connect.py", line 142, in run
    pwncat.victim.connect(client)
  File "/root/Downloads/pwncat/pwncat/remote/victim.py", line 289, in connect
    self.probe_host_details()
  File "/root/Downloads/pwncat/pwncat/remote/victim.py", line 514, in probe_host_details
    with self.open("/proc/1/comm", "r") as filp:
  File "/root/Downloads/pwncat/pwncat/remote/victim.py", line 1255, in open
    pipe = self.open_read(path, mode)
  File "/root/Downloads/pwncat/pwncat/remote/victim.py", line 1116, in open_read
    raise FileNotFoundError(f"No such file or directory: '{path}'")
FileNotFoundError: No such file or directory: '/proc/1/comm'```

**Comment by calebstewart** [comment]
I can make the changes to make this not die when loading (it shouldn't so this is a bug), however if I had to guess, this appears to be a difference between BSD and Linux, as `/proc/1/comm` should always exist on Linux to my understanding. It's the name of the binary which was executed to start the init process.

I should make a note in the documentation/README, but due to the numerous inconsistencies between BSD and Linux, I can't guarantee this tool will work consistently in a BSD environment. In fact some features I know are broken. This is because BSD uses different syntax with the same command name. It would be very difficult to handle every single difference in all the places that binaries are called. I don't explicitly refuse to start when a BSD system is identified, because if you are able to get a working busybox or something similar than most things should start working (busybox provides a consistent linux-like interface to common binaries that `pwncat` will prefer over system ones).
