### ISSUE TITLE
distutils not found

### ISSUE THREAD

**Issue by VainXploits** [calebstewart/pwncat#289]
## Bug Description
After installing pwncat using pip, facing an issue saying distutils not found

## pwncat version
Can't provide version because I can't run pwncat-cs because distutils is not found

## Target System (aka "victim")
My own kali box

```
┌──(root㉿vain)-[~]
└─# pwncat-cs -lp 4444                            
Traceback (most recent call last):
  File "/usr/local/bin/pwncat-cs", line 5, in <module>
    from pwncat.__main__ import main
  File "/usr/local/lib/python3.12/dist-packages/pwncat/__main__.py", line 11, in <module>
    import pwncat.manager
  File "/usr/local/lib/python3.12/dist-packages/pwncat/manager.py", line 43, in <module>
    import zodburi
  File "/usr/local/lib/python3.12/dist-packages/zodburi/__init__.py", line 2, in <module>
    from pkg_resources import iter_entry_points
  File "/usr/local/lib/python3.12/dist-packages/pkg_resources/__init__.py", line 90, in <module>
    import packaging.markers
  File "/usr/local/lib/python3.12/dist-packages/packaging/markers.py", line 25, in <module>
    from .specifiers import InvalidSpecifier, Specifier
  File "/usr/local/lib/python3.12/dist-packages/packaging/specifiers.py", line 14, in <module>
    from .utils import canonicalize_version
  File "/usr/local/lib/python3.12/dist-packages/packaging/utils.py", line 9, in <module>
    from .tags import Tag, parse_tag
  File "/usr/local/lib/python3.12/dist-packages/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils'
```

Above is the error that pops up whenever `pwncat-cs` is run with any flag after it.

**Comment by scmanjarrez** [comment]
This is a problem with latest python version in kali (3.12).
If you have a previous python version, then you can try installing `setuptools` and see [if that fixes the problem for you](https://stackoverflow.com/a/76691103/4305230).
```
pip install setuptools
```
If your python version is 3.12, then you'll need to do some manual updates:
First, install a pwncat with the new setuptools changes
```
pip install --force-reinstall git+https://github.com/scmanjarrez/pwncat
```
Next you need to update a pwncat dependency with the changes applied for setuptools
```
pip install git+https://github.com/Pylons/zodburi@modernize-python-versions
```
Pip will complain but ignore it, by this time pwncat should work again
```
❯ pwncat-cs -l -p 8000
/home/kali/htb/machines/hard/Yummy/venv/lib/python3.12/site-packages/paramiko/pkey.py:158: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  'cipher': algorithms.TripleDES,
/home/kali/htb/machines/hard/Yummy/venv/lib/python3.12/site-packages/paramiko/transport.py:178: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
  'class': algorithms.Blowfish,
/home/kali/htb/machines/hard/Yummy/venv/lib/python3.12/site-packages/paramiko/transport.py:202: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  'class': algorithms.TripleDES,
Ignoring index for /home/kali/htb/machines/hard/Yummy/pwncat/db/pwncat
[12:38:40] Welcome to pwncat 🐈!                                                                                                                                                                                                __main__.py:164
bound to 0.0.0.0:8000
```

> The warnings apparently can be removed by uninstalling paramiko-ng and installing paramiko package instead. 
> P.S: Haven't tested enough to confirm that this is an in-place replacement.

**Comment by nikallass** [comment]
Hi all.

1) to fix "No module named 'distutils'" error - add `setuptools = "^70.0"` to pyproject.toml in `[tool.poetry.dependencies]` section;
2) to fix "TripleDES \ Blowfish warnings" add `cryptography = "^36.0.0"` to pyproject.toml in `[tool.poetry.dependencies]` section;
3) use `pipx install /path/to/pwncat/cloned/git/dir`.

**Comment by sagisar1** [comment]
Hi, I Have the same problem, because I am using kali linux with python 3.12, and unfortunately, python 3.11 or 3.10 in which distutils wasn't deprecated yet, is not available in kali linux directly.

installing setuptools doesn't fix the problem.

anyway , since the author says in the README file of the tool:

> pwncat requires Python 3.9+ on Linux

 I suggest replacing distutils with something that works along all python3.9+ versions

**Comment by ku4979p9** [comment]
https://github.com/pyenv/pyenv

**Comment by sagisar1** [comment]
@ku4979p9  *** Update: I have suceeded to use pwncat with python3.11 through a virtual environment, as you propose here. however, it required me to built python3.11 fron source which took some time. @VainXploits this method should solve your problem since distutils is supported in python3.11
I still think that the maintainers of this repository (pwncat-cs) should make the adjusments in order to fit pwncat-cs also to python 3.12

**Comment by 4D7220426C7565** [comment]
Maybe if it has happened to someone, when you run: `pwncat-cs -lp port` and you get an error like: `ImportError: No module named 'readline'`

This error typically occurs because the `readline` module isn't installed in your Python environment.

```sh
sudo apt-get update
sudo apt-get install libreadline-dev
```

And if you get the error: `distutils not found` do the same procedure of [@scmanjarrez](https://github.com/calebstewart/pwncat/issues/289#issuecomment-2395387192)

**Comment by sagisar1** [comment]
@4D7220426C7565 what is this connected to this issue man?

**Comment by ku4979p9** [comment]
`pipx install pwncat-cs --python /home/kali/.pyenv/versions/3.11.10/bin/python3`
Set it as the executable file for python311, and then you can use it anywhere.
