### ISSUE TITLE
setup.py fails with python

### ISSUE THREAD

**Issue by pyroot99** [calebstewart/pwncat#31]
I tried installing with python as in from the readme.txt but I encountered an error, however, with python3 it installed successfully 
<img width="1186" alt="Screenshot 2020-07-17 at 12 44 55 PM" src="https://user-images.githubusercontent.com/31597287/87759429-edfab180-c82b-11ea-9de3-dcd6a7a8f19b.png">

**Comment by calebstewart** [comment]
You appear to be using python 2.7 vice python3.

**Comment by tostercx** [comment]
Which versions are currently supported btw? I tried 3.6/3.7 but it don't seem to have a shlex.join

https://github.com/calebstewart/pwncat/blob/95877fa160bcc3822ac040143dace505d7b5b37f/pwncat/__main__.py#L29

Upgraded to 3.8.4 but now it seems to be complaining about some recv params:

```
$ pwncat --ssh -u xxx -H yyy.com --password zzz
Traceback (most recent call last):
  File "/home/testb0x/.local/bin/pwncat", line 33, in <module>
    sys.exit(load_entry_point('pwncat==0.3.0', 'console_scripts', 'pwncat')())
  File "/home/testb0x/.local/lib/python3.8/site-packages/pwncat/__main__.py", line 28, in main
    pwncat.victim.command_parser.dispatch_line(
  File "/home/testb0x/.local/lib/python3.8/site-packages/pwncat/commands/__init__.py", line 290, in dispatch_line
    command.run(args)
  File "/home/testb0x/.local/lib/python3.8/site-packages/pwncat/commands/connect.py", line 229, in run
    pwncat.victim.connect(chan)
  File "/home/testb0x/.local/lib/python3.8/site-packages/pwncat/remote/victim.py", line 279, in connect
    hostname_path = self.run("which hostname").strip().decode("utf-8")
  File "/home/testb0x/.local/lib/python3.8/site-packages/pwncat/remote/victim.py", line 1035, in run
    sdelim, edelim = self.process(cmd, delim=wait, timeout=timeout)
  File "/home/testb0x/.local/lib/python3.8/site-packages/pwncat/remote/victim.py", line 1089, in process
    data = self.client.recv(len(command), socket.MSG_PEEK)
TypeError: recv() takes 2 positional arguments but 3 were given```

**Comment by calebstewart** [comment]
I will add a note that `pwncat` requires Python 3.8 in the README/docs, but yes the second issue is due to the custom paramiko fork as you found. I can make a more explicit note of that specific error in the README as well.
