### ISSUE TITLE
[BUG] install

### ISSUE THREAD

**Issue by FHaskell** [calebstewart/pwncat#76]
gives me this error when I try to install from the pip github:
```
# pip install git+https://github.com/calebstewart/pwncat.git
Collecting git+https://github.com/calebstewart/pwncat.git
  Cloning https://github.com/calebstewart/pwncat.git to /tmp/pip-ksmQ_B-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ksmQ_B-build/setup.py", line 67
        dependency_links[i] = f"{link}/tarball/master#egg={name}"
                                                                ^
    SyntaxError: invalid syntax

```
and a similar error when I clone it and run:
```
# python setup.py install
  File "setup.py", line 67
    dependency_links[i] = f"{link}/tarball/master#egg={name}"
```

**Comment by JohnHammond** [comment]
That looks to be an error on a line that uses an f-string. What version of
Python are you using? Pwncat requires 3.8 or higher.

**Comment by FHaskell** [comment]
Aha, current python is 3.6.6 so I ran:
```
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:deadsnakes/ppa
$ sudo apt-get update
$ sudo apt-get install python3.8
```
and it said:
```
root@kali:~# sudo apt-get install python3.8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.2.0-4 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by FHaskell** [comment]
nevermind, updated to python 3.9.1, get the same error about the f-string.

**Comment by tsustyle** [comment]
Have you tried `python3 setup.py install` ?

**Comment by FHaskell** [comment]
Yes, gives the same error.

**Comment by FHaskell** [comment]
I installed python3, I've installed setuptools for python3 and python2, I've adjusted the path names to point at it, but every time I run it I get the same error: missing setuptools

**Comment by calebstewart** [comment]
Debian commonly has problems with pip, setuptools, and wheel versions. 

The packages installed globally (like setuptools) does not translate to your virtualenv, so have you run `python3 -m pip install -U pip setuptools`? That should install and/or upgrade pip itself and setuptools. Ensure you have activated the virtual environment first, so that you operate on that virtual environment. If you are trying to install without a virtualenv, then you should be able to run the same command regardless and it should upgrade/install `pip` and `setuptools` (although, it is recommended to use a virtualenv to avoid dependency conflicts with system packages).

**Comment by trevorbryant** [comment]
@FHaskell, were you able to get your python environment setup and running?

**Comment by FHaskell** [comment]
I was not. But OffSec just released a new version of Kali so I'll upgrade to that and see if it works.

**Comment by calebstewart** [comment]
There's been no activity here for over 2 months. I'm going to close this issue. Feel free to reach out if you are still having issues.
