### ISSUE TITLE
Module requests missing in requirements.txt

### ISSUE THREAD

**Issue by Brazier85** [calebstewart/pwncat#9]
On my notebook i had to add `requests`to the requirements.txt to get rid of the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xx/src/pwncat/pwncat/__main__.py", line 8, in <module>
    from pwncat.pty import PtyHandler
  File "/home/xx/src/pwncat/pwncat/pty.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by JohnHammond** [comment]
Oh, good catch! Thank you, we'll make sure that is explicitly in the requirements.txt.
